
version: 2

models:
    - name: hevotrial
      description: "A model for loading the output of the clv for customers"
      columns:
          - name: c_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
